# Generated by Django 4.1 on 2022-08-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0002_createpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
