# Generated by Django 4.1 on 2022-08-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePost',
        ),
    ]
