# Generated by Django 4.1 on 2022-08-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0004_delete_createpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
