# Generated by Django 4.1 on 2022-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0005_remove_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to='photos/posts'),
            preserve_default=False,
        ),
    ]
