# Generated by Django 4.1 on 2022-08-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0008_remove_post_images_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
