# Generated by Django 4.1 on 2022-08-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0010_post_images_post_slug_alter_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
