# Generated by Django 4.1 on 2022-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0012_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_nmumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
