# Generated by Django 4.1 on 2022-09-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksgposts', '0013_post_phone_nmumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
