# Generated by Django 4.1 on 2022-09-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='state',
            new_name='county',
        ),
    ]
