# Generated by Django 4.1 on 2022-08-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
    ]
