# Generated by Django 4.1 on 2022-08-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_category_category_image_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
