# Generated by Django 4.1 on 2022-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_category_cat_image_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default=1, upload_to='photos/categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
